'use strict';

module.exports = {
  rules: {
    'link-href-attributes': 'error',
    'no-abstract-roles': 'error',
    'no-accesskey-attribute': 'error',
    'no-aria-hidden-body': 'error',
    'no-autofocus-attribute': 'error',
    'no-down-event-binding': 'error',
    'no-duplicate-attributes': 'error',
    'no-duplicate-id': 'error',
    'no-duplicate-landmark-elements': 'error',
    'no-empty-headings': 'error',
    'no-heading-inside-button': 'error',
    'no-invalid-interactive': 'error',
    'no-invalid-link-text': 'error',
    'no-invalid-link-title': 'error',
    'no-invalid-meta': 'error',
    'no-invalid-role': 'error',
    'no-nested-interactive': 'error',
    'no-nested-landmark': 'error',
    'no-obsolete-elements': 'error',
    'no-positive-tabindex': 'error',
    'no-redundant-landmark-role': 'error',
    'no-whitespace-for-layout': 'error',
    'no-whitespace-within-word': 'error',
    'require-context-role': 'error',
    'require-iframe-title': 'error',
    'require-input-label': 'error',
    'require-lang-attribute': 'error',
    'require-presentational-children': 'error',
    'require-valid-alt-text': 'error',
    'table-groups': 'error',
  },
};
