// STOP: This file is autogenerated by: npm run update:indices

import _4xrecommended from './4-x-recommended.js';
import a11y from './a11y.js';
import recommended from './recommended.js';
import stylistic from './stylistic.js';

export default {
  '4-x-recommended': _4xrecommended,
  a11y,
  recommended,
  stylistic,
};
