// STOP: This file is autogenerated by: npm run update:indices

import _5xrecommended from './5-x-recommended.js';
import a11y from './a11y.js';
import recommended from './recommended.js';
import stylistic from './stylistic.js';

export default {
  '5-x-recommended': _5xrecommended,
  a11y,
  recommended,
  stylistic,
};
