// STOP: This file is autogenerated by: npm run update:indices

import _3xrecommended from './3-x-recommended.js';
import a11y from './a11y.js';
import recommended from './recommended.js';
import stylistic from './stylistic.js';

export default {
  '3-x-recommended': _3xrecommended,
  a11y,
  recommended,
  stylistic,
};
